### ISSUE TITLE
[bug] problems with TextClock

### ISSUE THREAD

**Issue by jrpie** [jrpie/launcher#150]
### Describe the Bug

```markdown
(reported by mail)

Around second 59 or so, the GUI rushes.
59,00,01 ...

This was introduced a few updates ago [comment: Should be around the time when the custom clock implementation was scrapped and replaced by Android's TextClock]

Sometimes the 'selectable area' around the clock (pressed to launch an alarm app f.i.)
rests visible, a bit more dimmed than the rest of the background - like the haptic feedback of selelecting that area didn't refresh?
```

### Expected Behavior

```markdown
The clock should advance one second per second. The background should not be visible
```

### To Reproduce

```markdown
So far I (@jrpie) was unable to reproduce this bug.
```

### Your Device

```markdown
samsung J4+ / android 9
```

**Comment by wassupluke** [comment]
I was also unable to reproduce this on...
```yml
µLauncher version: 0.1.4 (44)
Android version: 16 (sdk 36)
Model: Pixel 8 Pro
Device: husky
Brand: google
Manufacturer: Google
```
